/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as SneakersIdRouteImport } from './routes/sneakers/$id'
import { Route as AppCollectionsIndexRouteImport } from './routes/_app/collections/index'
import { Route as AppManageChar123TabChar125RouteImport } from './routes/_app/manage.{-$tab}'
import { Route as AppCollectionsIdRouteImport } from './routes/_app/collections/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const SneakersIdRoute = SneakersIdRouteImport.update({
  id: '/sneakers/$id',
  path: '/sneakers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCollectionsIndexRoute = AppCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppManageChar123TabChar125Route =
  AppManageChar123TabChar125RouteImport.update({
    id: '/manage/{-$tab}',
    path: '/manage/{-$tab}',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppCollectionsIdRoute = AppCollectionsIdRouteImport.update({
  id: '/collections/$id',
  path: '/collections/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/sneakers/$id': typeof SneakersIdRoute
  '/collections/$id': typeof AppCollectionsIdRoute
  '/manage/{-$tab}': typeof AppManageChar123TabChar125Route
  '/collections/': typeof AppCollectionsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/sneakers/$id': typeof SneakersIdRoute
  '/': typeof AppIndexRoute
  '/collections/$id': typeof AppCollectionsIdRoute
  '/manage/{-$tab}': typeof AppManageChar123TabChar125Route
  '/collections': typeof AppCollectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/sneakers/$id': typeof SneakersIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/collections/$id': typeof AppCollectionsIdRoute
  '/_app/manage/{-$tab}': typeof AppManageChar123TabChar125Route
  '/_app/collections/': typeof AppCollectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sneakers/$id'
    | '/collections/$id'
    | '/manage/{-$tab}'
    | '/collections/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/sneakers/$id'
    | '/'
    | '/collections/$id'
    | '/manage/{-$tab}'
    | '/collections'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/sneakers/$id'
    | '/_app/'
    | '/_app/collections/$id'
    | '/_app/manage/{-$tab}'
    | '/_app/collections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SneakersIdRoute: typeof SneakersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/sneakers/$id': {
      id: '/sneakers/$id'
      path: '/sneakers/$id'
      fullPath: '/sneakers/$id'
      preLoaderRoute: typeof SneakersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/collections/': {
      id: '/_app/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof AppCollectionsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/manage/{-$tab}': {
      id: '/_app/manage/{-$tab}'
      path: '/manage/{-$tab}'
      fullPath: '/manage/{-$tab}'
      preLoaderRoute: typeof AppManageChar123TabChar125RouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/collections/$id': {
      id: '/_app/collections/$id'
      path: '/collections/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof AppCollectionsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCollectionsIdRoute: typeof AppCollectionsIdRoute
  AppManageChar123TabChar125Route: typeof AppManageChar123TabChar125Route
  AppCollectionsIndexRoute: typeof AppCollectionsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCollectionsIdRoute: AppCollectionsIdRoute,
  AppManageChar123TabChar125Route: AppManageChar123TabChar125Route,
  AppCollectionsIndexRoute: AppCollectionsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SneakersIdRoute: SneakersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
